### PR TITLE
Suggested edits for https://github.com/DevExpress/DevExtreme.AspNet.Data/pull/205

### PR DESCRIPTION
**Pull request by AlekseyMartynov**

### CODE REVIEW

**Comment by olegbevz** [comment]
If we want to care about thread safety and resource disposal I would converted CustomAggregators to singleton instead of having CustomAggregatorsBarrier:

```
    public class CustomAggregators {
        private static readonly CustomAggregators _instance = new CustomAggregators();
        private readonly Dictionary<string, Type> _aggregatorTypes = new Dictionary<string, Type>();

        internal CustomAggregators() {
        }

        public static void RegisterAggregator(string summaryType, Type aggregatorType) {
            _instance.RegisterAggregatorInternal(summaryType, aggregatorType);
        }

        internal void RegisterAggregatorInternal(string summaryType, Type aggregatorType) {
            _aggregatorTypes[summaryType] = aggregatorType;
        }

        internal Aggregator<T> CreateAggregator<T>(string summaryType, IAccessor<T> accessor) {
            if (_aggregatorTypes.TryGetValue(summaryType, out var aggregatorType)) {
                var genericAggregatorType = aggregatorType.MakeGenericType(typeof(T));
                return (Aggregator<T>)Activator.CreateInstance(genericAggregatorType, accessor);
            }

            return null;
        }
    }
```
And then in tests we can just create class instance:

```
var customAggregators = new CustomAggregators();
customAggregators.RegisterAggregatorInternal("sum", typeof(SumAggregator<>));
```

Anyway I can merge your code.

**Comment by AlekseyMartynov** [comment]
How the `AggregateCalculatorTests.CustomAggregator` case would look then?

**Comment by olegbevz** [comment]
In AggregateCalculatorTests.CustomAggregator we can use static register method:
```
CustomAggregators.RegisterAggregator("comma", typeof(CommaAggregator<>));
```
Static aggregators collection should not conflict with other unit tests where instance of CustomAggregators will be used.
Or we can create an instance of CustomAggregators and pass it to AggregateCalculator constructor:
```
var customAggregators = new CustomAggregators();
customAggregators.RegisterAggregatorInternal("sum", typeof(SumAggregator<>));
var calculator = new AggregateCalculator<int>(data, new DefaultAccessor<int>(),
                new[] { new SummaryInfo { Selector = "this", SummaryType = "comma" } },
                new[] { new SummaryInfo { Selector = "this", SummaryType = "comma" } }
            ), customAggregators);
```

**Comment by AlekseyMartynov** [comment]
> Static aggregators collection should not conflict with other unit tests where instance of CustomAggregators will be used.

Sure. However, a conflict will arise with the next test case (in another class) accessing the static collection.

 > Or we can create an instance of CustomAggregators and pass it to AggregateCalculator constructor

Ultimately, the goal is to cover end-user scenarios. If we inject `CustomAggregators` into `AggregateCalculator` then we need another test ensuring that the public API works.

Do you see any issues with `CustomAggregatorsBarrier`?

**Comment by olegbevz** [comment]
Lambda expressions are often hard to debug and you have to duplicate CustomAggregatorsBarrier code in each test. Perhaps to test static classes each test should be run in separate AppDomain. Not sure if it is supported by xunit. Perhaps you will change it later. Now I will do the merge

**Pull request merged**
